### ISSUE TITLE
Missed QUICHE_ERR_BUFFER_TOO_SHORT in QuicError enum

### ISSUE THREAD

**Issue by atropnikov** [netty/netty-incubator-codec-quic#111]
io.netty.incubator.codec.quic.Quiche#QUICHE_ERR_BUFFER_TOO_SHORT is missed in io.netty.incubator.codec.quic.QuicError.  

That causes the following error:

```
java.lang.IllegalArgumentException: unknown QuicError code: -2
        at io.netty.incubator.codec.quic.QuicError.valueOf(QuicError.java:71) ~[vpnendpoint.jar:?]
        at io.netty.incubator.codec.quic.Quiche.errorAsString(Quiche.java:514) ~[vpnendpoint.jar:?]
        at io.netty.incubator.codec.quic.QuicheQuicCodec.channelRead(QuicheQuicCodec.java:173) ~[vpnendpoint.jar:?]
        at io.netty.incubator.codec.quic.QuicheQuicCodec.channelRead(QuicheQuicCodec.java:134) ~[vpnendpoint.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [vpnendpoint.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [vpnendpoint.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [vpnendpoint.jar:?]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [vpnendpoint.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [vpnendpoint.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [vpnendpoint.jar:?]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [vpnendpoint.jar:?]
        at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:93) [vpnendpoint.jar:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) [vpnendpoint.jar:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) [vpnendpoint.jar:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) [vpnendpoint.jar:?]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [vpnendpoint.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [vpnendpoint.jar:?]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [vpnendpoint.jar:?]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [vpnendpoint.jar:?]
        at java.lang.Thread.run(Thread.java:832) [?:?]
```

**Comment by normanmaurer** [comment]
@atropnikov we love PRs if you are up to provide a fix :)

**Comment by atropnikov** [comment]
@normanmaurer I will provide PR soon. I just wonder if it wasn't added intentionally for some reason.

**Comment by normanmaurer** [comment]
@atropnikov I guess it can happen that you see the a "too short buffer" in the real world if there is a truncated datagram.

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty-incubator-codec-quic/pull/112
