### ISSUE TITLE
GraalVM native image runtime exception: UnsatisfiedLinkError - io.netty.incubator.codec.quic.BoringSSL.SSLContext_new

### ISSUE THREAD

**Issue by zipper01** [netty/netty-incubator-codec-quic#464]
Environment:

    Version info: 'GraalVM 22.3.0 Java 17 CE'
    Java version info: '17.0.5+8-jvmci-22.3-b08'
    C compiler: gcc (redhat, x86_64, 8.5.0)
    OS: CentOS 8.2

Netty dependencies:

        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-buffer</artifactId>
            <version>4.1.86.Final</version>
        </dependency>
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-handler</artifactId>
            <version>4.1.86.Final</version>
        </dependency>
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-codec-http</artifactId>
            <version>4.1.86.Final</version>
        </dependency>
        <dependency>
            <groupId>io.netty.incubator</groupId>
            <artifactId>netty-incubator-codec-native-quic</artifactId>
            <version>0.0.35.Final</version>
            <classifier>linux-x86_64</classifier>
        </dependency>

Error:

    Exception in thread "Thread-3" java.lang.UnsatisfiedLinkError: io.netty.incubator.codec.quic.BoringSSL.SSLContext_new0(Z[BLjava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;I[[B)J [symbol: Java_io_netty_incubator_codec_quic_BoringSSL_SSLContext_1new0 or Java_io_netty_incubator_codec_quic_BoringSSL_SSLContext_1new0__Z_3BLjava_lang_Object_2Ljava_lang_Object_2Ljava_lang_Object_2Ljava_lang_Object_2Ljava_lang_Object_2Ljava_lang_Object_2Ljava_lang_Object_2I_3_3B]
            at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.access.JNINativeLinkage.getOrFindEntryPoint(JNINativeLinkage.java:152)
            at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.JNIGeneratedMethodSupport.nativeCallAddress(JNIGeneratedMethodSupport.java:53)
            at io.netty.incubator.codec.quic.BoringSSL.SSLContext_new0(BoringSSL.java)
            at io.netty.incubator.codec.quic.BoringSSL.SSLContext_new(BoringSSL.java:50)
            at io.netty.incubator.codec.quic.QuicheQuicSslContext.<init>(QuicheQuicSslContext.java:109)
            at io.netty.incubator.codec.quic.QuicSslContextBuilder.build(QuicSslContextBuilder.java:374)
            at com.stellarvia.relaysys.common.net.QuicStreamChannelHandler.connect(QuicStreamChannelHandler.java:118)
            at com.stellarvia.relaysys.common.net.ClientEndpoint.connect(ClientEndpoint.java:103)
            at com.stellarvia.relaysys.relayagent.AgentMgr$2.run(AgentMgr.java:340)
            at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:775)
            at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:203)

**Comment by normanmaurer** [comment]
Sorry but someone lese will need to chime in and provide a PR for this. my Graal knowhow is very limited

**Comment by normanmaurer** [comment]
@violetagg can you help with this one ?

**Comment by violetagg** [comment]
> @violetagg can you help with this one ?

Yep I'll see what we need (I'm just returning from vacation, I'll need some time to catch up with all that I missed)

**Comment by normanmaurer** [comment]
@violetagg any idea ?
