### ISSUE TITLE
New version 0.0.37.Final results in ConnectTimeoutException: connection timed out

### ISSUE THREAD

**Issue by violetagg** [netty/netty-incubator-codec-quic#482]
When I run `Netty QUIC Codec` examples with version `0.0.36.Final`, the examples are executed as expected. When I switch to version `0.0.37.Final`, `ConnectTimeoutException: connection timed out` is thrown.

```
Exception in thread "main" java.util.concurrent.ExecutionException: io.netty.channel.ConnectTimeoutException: connection timed out: QuicConnectionAddress{EPHEMERAL}
	at io.netty.util.concurrent.DefaultPromise.get(DefaultPromise.java:351)
	at org.example.QuicClientExample.main(QuicClientExample.java:77)
Caused by: io.netty.channel.ConnectTimeoutException: connection timed out: QuicConnectionAddress{EPHEMERAL}
	at io.netty.incubator.codec.quic.QuicheQuicChannel$QuicChannelUnsafe.lambda$connect$1(QuicheQuicChannel.java:1298)
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:153)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:750)
```

Here is a reproducible example (the code is copied from `Netty QUIC Codec` examples)
https://github.com/violetagg/netty-quic-codec-connection-timed-out

**OS**
Mac OS M1

**Java**
JDK 8

I'm seeing this issue on other OSes also
Reactor Netty CI https://github.com/reactor/reactor-netty/actions/runs/4353576745

**Comment by normanmaurer** [comment]
Interesting... At least when I run these from within the main branch all works as expected ... Can you check what happens for you ?

**Comment by violetagg** [comment]
Ok, on a system where `netty-incubator-codec-quic` is NOT built, this example is not working. On a system where `netty-incubator-codec-quic` is built - it is working.

**Comment by violetagg** [comment]
Yes

See the link to the Reactor Netty CI in the description

**Comment by normanmaurer** [comment]
I need to debug this somehow... No idea what happened here. We upgraded the quiche version tho, but it's very strange that it works when you compile it yourself.

**Comment by violetagg** [comment]
I’ll also continue playing with it, let’s see whether I’ll be able to find
something

**Comment by normanmaurer** [comment]
@violetagg I just did run your example on another laptop (not the one I released quic on). It "just works"....

**Comment by violetagg** [comment]
OS 
`Linux instance-1 5.15.0-1030-gcp #37-Ubuntu SMP Tue Feb 14 19:37:08 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`

Java

```
openjdk version "1.8.0_362"
OpenJDK Runtime Environment (build 1.8.0_362-8u362-ga-0ubuntu1~22.04-b09)
OpenJDK 64-Bit Server VM (build 25.362-b09, mixed mode)
```

The example fails with
```
java.util.concurrent.ExecutionException: io.netty.channel.ConnectTimeoutException: connection timed out: QuicConnectionAddress{EPHEMERAL}
```

When I switch to
```
openjdk version "11.0.18" 2023-01-17
OpenJDK Runtime Environment (build 11.0.18+10-post-Ubuntu-0ubuntu122.04)
OpenJDK 64-Bit Server VM (build 11.0.18+10-post-Ubuntu-0ubuntu122.04, mixed mode, sharing)
```

I am able to see `Hello World!`

**Comment by normanmaurer** [comment]
Alright... I know what the problem is:

```
java.lang.NoSuchMethodError: java.nio.ByteBuffer.position(I)Ljava/nio/ByteBuffer;
```

There must have been something wrong while doing the release. Let me ensure this will not happen again and do a release.

**Comment by normanmaurer** [comment]
Ok I found the problem... The release was build with JDK17 🤦

**Comment by violetagg** [comment]
Perfect! Reactor Netty CI is green with `0.0.38.Final`. Thanks a lot!
