### ISSUE TITLE
 how to fix it "crash on Android when load a native library: netty_quiche"

### ISSUE THREAD

**Issue by huayuxian** [netty/netty-incubator-codec-quic#642]
hello  ,when test app execute quic's demo, the following error is reported on the android test device,
[](url)  , how to fix it 
device version : android os  6.0+
cpu:  arm64-v8a   
min-ndk: 23
netty  library version:  io.netty.incubator:netty-incubator-codec-native-quic:0.0.51.Final:android@aar

![111](https://github.com/netty/netty-incubator-codec-quic/assets/5334657/13ca1d2c-924a-44fe-acc0-4461033e67da)

 No implementation found for java.lang.String io.netty.incubator.codec.quic.Quiche.quiche_version() (tried Java_io_netty_incubator_codec_quic_Quiche_quiche_1version and Java_io_netty_incubator_codec_quic_Quiche_quiche_1version__)
01-04 23:45:18.491 16372-16597/com.test [E/AndroidRuntime:](url) FATAL EXCEPTION: Thread-800
    Process: com.test, PID: 16372
    java.lang.UnsatisfiedLinkError: failed to load the required native library
        at io.netty.incubator.codec.quic.Quic.ensureAvailability(Quic.java:78)
        at io.netty.incubator.codec.quic.QuicheQuicSslContext.<init>(QuicheQuicSslContext.java:75)
        at io.netty.incubator.codec.quic.QuicSslContextBuilder.build(QuicSslContextBuilder.java:374)
        at com.test.net.quic.QuicClient.request(QuicClient.java:28)
        at com.test.base.MyApplication$1.run(MyApplication.java:92)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: java.lang.UnsatisfiedLinkError: could not load a native lib No implementation found for java.lang.String io.netty.incubator.codec.quic.Quiche.quiche_version() (tried Java_io_netty_incubator_codec_quic_Quiche_quiche_1version and Java_io_netty_incubator_codec_quic_Quiche_quiche_1version__)
01-04 23:45:18.491 16372-16597/com.test.pro E/AndroidRuntime: FATAL EXCEPTION: Thread-800
    Process: com.test, PID: 16372
    java.lang.UnsatisfiedLinkError: failed to load the required native library
        at io.netty.incubator.codec.quic.Quic.ensureAvailability(Quic.java:78)
        at io.netty.incubator.codec.quic.QuicheQuicSslContext.<init>(QuicheQuicSslContext.java:75)
        at io.netty.incubator.codec.quic.QuicSslContextBuilder.build(QuicSslContextBuilder.java:374)
        at com.tet.net.quic.QuicClient.request(QuicClient.java:28)
        at com.test.MyApplication$1.run(MyApplication.java:92)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: java.lang.UnsatisfiedLinkError: could not load a native library: netty_quiche
        at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:239)
        at io.netty.incubator.codec.quic.Quiche.loadNativeLibrary(Quiche.java:77)
        at io.netty.incubator.codec.quic.Quiche.<clinit>(Quiche.java:57)
        at io.netty.incubator.codec.quic.Quiche.quiche_version(Native Method)
        at io.netty.incubator.codec.quic.Quic.<clinit>(Quic.java:43)
        at io.netty.incubator.codec.quic.QuicheQuicSslContext.<init>(QuicheQuicSslContext.java:75) 
        at io.netty.incubator.codec.quic.QuicSslContextBuilder.build(QuicSslContextBuilder.java:374) 
        at com.test.net.quic.QuicClient.request(QuicClient.java:28) 
        at com.test.MyApplication$1.run(MyApplication.java:92) 
        at java.lang.Thread.run(Thread.java:818) 
     Caused by: java.io.FileNotFoundException: META-INF/native/libnetty_quiche.so
        at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:186)
        at io.netty.incubator.codec.quic.Quiche.loadNativeLibrary(Quiche.java:77) 
        at io.netty.incubator.codec.quic.Quiche.<clinit>(Quiche.java:57) 
        at io.netty.incubator.codec.quic.Quiche.quiche_version(Native Method) 
        at io.netty.incubator.codec.quic.Quic.<clinit>(Quic.java:43) 
        at io.netty.incubator.codec.quic.QuicheQuicSslContext.<init>(QuicheQuicSslContext.java:75) 
        at io.netty.incubator.codec.quic.QuicSslContextBuilder.build(QuicSslContextBuilder.java:374) 
        at com.test.net.quic.QuicClient.request(QuicClient.java:28) 
        at com.test.MyApplication$1.run(MyApplication.java:92) 
        at java.lang.Thread.run(Thread.java:818) rary: netty_quiche
        at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:239)
        at io.netty.incubator.codec.quic.Quiche.loadNativeLibrary(Quiche.java:77)
        at io.netty.incubator.codec.quic.Quiche.<clinit>(Quiche.java:57)
        at io.netty.incubator.codec.quic.Quiche.quiche_version(Native Method)
        at io.netty.incubator.codec.quic.Quic.<clinit>(Quic.java:43)
        at io.netty.incubator.codec.quic.QuicheQuicSslContext.<init>(QuicheQuicSslContext.java:75) 
        at io.netty.incubator.codec.quic.QuicSslContextBuilder.build(QuicSslContextBuilder.java:374) 
        at com.test.net.quic.QuicClient.request(QuicClient.java:28) 
        at com.test.MyApplication$1.run(MyApplication.java:92) 
        at java.lang.Thread.run(Thread.java:818) 
     Caused by: java.io.FileNotFoundException: META-INF/native/libnetty_quiche.so
        at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:186)
        at io.netty.incubator.codec.quic.Quiche.loadNativeLibrary(Quiche.java:77) 
        at io.netty.incubator.codec.quic.Quiche.<clinit>(Quiche.java:57) 
        at io.netty.incubator.codec.quic.Quiche.quiche_version(Native Method) 
        at io.netty.incubator.codec.quic.Quic.<clinit>(Quic.java:43) 
        at io.netty.incubator.codec.quic.QuicheQuicSslContext.<init>(QuicheQuicSslContext.java:75) 
        at io.netty.incubator.codec.quic.QuicSslContextBuilder.build(QuicSslContextBuilder.java:374) 
        at com.test.net.quic.QuicClient.request(QuicClient.java:28) 
        at com.test.MyApplication$1.run(MyApplication.java:92) 
        at java.lang.Thread.run(Thread.java:818)

**Comment by normanmaurer** [comment]
We dont public android builds... You will need to build it yourself.
