### ISSUE TITLE
javax.net.ssl.SSLException: QUICHE_ERR_CRYPTO_FAIL

### ISSUE THREAD

**Issue by heixiaoma** [netty/netty-incubator-codec-quic#681]
I encountered this error, and I'm not sure if it will affect the issue of memory growth.

```
2024-03-02 03:55:48.142  WARN --- [ventLoopGroup-2-1] i.n.c.AbstractChannelHandlerContext      [ 355] : An exception 'java.lang.NullPointerException' [enable DEBUG level for full stacktrace] was thrown by a user handler's exceptionCaught() method while handling the following exception:
javax.net.ssl.SSLException: QUICHE_ERR_CRYPTO_FAIL
	at io.netty.incubator.codec.quic.Quiche.newException(Quiche.java:794)
	at io.netty.incubator.codec.quic.Quiche.throwIfError(Quiche.java:808)
	at io.netty.incubator.codec.quic.QuicheQuicChannel$QuicChannelUnsafe.connectionRecv(QuicheQuicChannel.java:1494)
	at io.netty.incubator.codec.quic.QuicheQuicChannel.recv(QuicheQuicChannel.java:865)
	at io.netty.incubator.codec.quic.QuicheQuicCodec.channelRecv(QuicheQuicCodec.java:313)
	at io.netty.incubator.codec.quic.QuicheQuicServerCodec.channelRecv(QuicheQuicServerCodec.java:105)
	at io.netty.incubator.codec.quic.QuicheQuicCodec$QuicCodecHeaderProcessor.process(QuicheQuicCodec.java:293)
	at io.netty.incubator.codec.quic.QuicHeaderParser.parse(QuicHeaderParser.java:127)
	at io.netty.incubator.codec.quic.QuicheQuicCodec.handleQuicPacket(QuicheQuicCodec.java:164)
	at io.netty.incubator.codec.quic.QuicheQuicCodec.channelRead(QuicheQuicCodec.java:155)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:97)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:750)
Caused by: io.netty.incubator.codec.quic.QuicException: QUICHE_ERR_CRYPTO_FAIL
	at io.netty.incubator.codec.quic.Quiche.newException(Quiche.java:780)
	... 25 common frames omitted
```

**Comment by heixiaoma** [comment]
I use Quic to transfer data, and after a few days, the memory will increase slightly until the system is shut down. However, I did not find any memory leaks or other issues. Of course, it may be due to my code logic. Currently, I see that the error is caused by this SSL throw, and this issue cannot be detected yet. I am using version 0.0.56.Final

**Comment by normanmaurer** [comment]
Let me close this for now... Please reopen if the issue still happens with latest release
