### ISSUE TITLE
NPE in Quiche error handling

### ISSUE THREAD

**Issue by poisonriver** [netty/netty-incubator-codec-quic#735]
I think it could be the missing mapping for QUICHE_ERR_STREAM_RESET in io.netty.incubator.codec.quic.Quiche

 java.lang.NullPointerException: Cannot read field "error" because "x0" is null
  at io.netty.incubator.codec.quic.Quiche$QuicTransportErrorHolder.access$000(Quiche.java:906)
  at io.netty.incubator.codec.quic.Quiche.convertToException(Quiche.java:893)
  at io.netty.incubator.codec.quic.QuicheQuicChannel.streamRecv(QuicheQuicChannel.java:948)
  at io.netty.incubator.codec.quic.QuicheQuicStreamChannel$QuicStreamChannelUnsafe.recv(QuicheQuicStreamChannel.java:950)
  at io.netty.incubator.codec.quic.QuicheQuicStreamChannel$QuicStreamChannelUnsafe.beginRead(QuicheQuicStreamChannel.java:626)
  at io.netty.channel.DefaultChannelPipeline$HeadContext.read(DefaultChannelPipeline.java:1359)
  at io.netty.channel.AbstractChannelHandlerContext.invokeRead(AbstractChannelHandlerContext.java:845)
  at io.netty.channel.AbstractChannelHandlerContext.read(AbstractChannelHandlerContext.java:824)
  at io.netty.incubator.codec.http3.Http3FrameCodec.read(Http3FrameCodec.java:635)
  at io.netty.channel.AbstractChannelHandlerContext.invokeRead(AbstractChannelHandlerContext.java:851)
  at io.netty.channel.AbstractChannelHandlerContext.read(AbstractChannelHandlerContext.java:824)
  at io.netty.incubator.codec.http3.Http3FrameTypeDuplexValidationHandler.read(Http3FrameTypeDuplexValidationHandler.java:85)
  at io.netty.channel.AbstractChannelHandlerContext.invokeRead(AbstractChannelHandlerContext.java:851)
  at io.netty.channel.AbstractChannelHandlerContext.read(AbstractChannelHandlerContext.java:824)
  at io.netty.channel.DefaultChannelPipeline.read(DefaultChannelPipeline.java:1003)
  at io.netty.channel.DefaultChannelPipeline.read(DefaultChannelPipeline.java:45)
  at io.netty.incubator.codec.quic.QuicheQuicStreamChannel.read(QuicheQuicStreamChannel.java:288)
  at io.netty.incubator.codec.quic.QuicheQuicStreamChannel.read(QuicheQuicStreamChannel.java:52)
  at io.netty.channel.DefaultChannelPipeline$HeadContext.readIfIsAutoRead(DefaultChannelPipeline.java:1419)
  at io.netty.channel.DefaultChannelPipeline$HeadContext.channelActive(DefaultChannelPipeline.java:1397)
  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:258)
  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:238)
  at io.netty.channel.DefaultChannelPipeline.fireChannelActive(DefaultChannelPipeline.java:894)
  at io.netty.incubator.codec.quic.QuicheQuicStreamChannel$QuicStreamChannelUnsafe.register(QuicheQuicStreamChannel.java:491)
  at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:89)
  at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:83)
  at io.netty.incubator.codec.quic.QuicheQuicChannel$1.onUnhandledInboundMessage(QuicheQuicChannel.java:436)
  at io.netty.channel.DefaultChannelPipeline$TailContext.channelRead(DefaultChannelPipeline.java:1293)
  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
  at io.netty.incubator.codec.http3.Http3ConnectionHandler.channelRead(Http3ConnectionHandler.java:180)
  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
  at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1407)
  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
  at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:918)
  at io.netty.incubator.codec.quic.QuicheQuicChannel$QuicChannelUnsafe.recvStream(QuicheQuicChannel.java:1830)
  at io.netty.incubator.codec.quic.QuicheQuicChannel$QuicChannelUnsafe.processReceived(QuicheQuicChannel.java:1709)
  at io.netty.incubator.codec.quic.QuicheQuicChannel$QuicChannelUnsafe.connectionRecv(QuicheQuicChannel.java:1644)
  at io.netty.incubator.codec.quic.QuicheQuicChannel.recv(QuicheQuicChannel.java:958)
  at io.netty.incubator.codec.quic.QuicheQuicCodec$QuicCodecHeaderProcessor.process(QuicheQuicCodec.java:373)
  at io.netty.incubator.codec.quic.QuicHeaderParser.parse(QuicHeaderParser.java:143)
  at io.netty.incubator.codec.quic.QuicheQuicCodec.handleQuicPacket(QuicheQuicCodec.java:202)
  at io.netty.incubator.codec.quic.QuicheQuicCodec.channelRead(QuicheQuicCodec.java:193)
  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
  at io.netty.incubator.codec.quic.QuicCodecDispatcher$ChannelHandlerContextDispatcher.fireChannelRead(QuicCodecDispatcher.java:304)
  at io.netty.incubator.codec.quic.QuicCodecDispatcher.channelRead(QuicCodecDispatcher.java:126)
  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
  at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1407)
  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
  at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:918)
  at io.netty.channel.epoll.EpollDatagramChannel.processPacket(EpollDatagramChannel.java:662)
  at io.netty.channel.epoll.EpollDatagramChannel.recvmsg(EpollDatagramChannel.java:697)
  at io.netty.channel.epoll.EpollDatagramChannel.access$300(EpollDatagramChannel.java:56)
  at io.netty.channel.epoll.EpollDatagramChannel$EpollDatagramChannelUnsafe.epollInReady(EpollDatagramChannel.java:536)
  at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:501)
  at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:399)
  at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:994)
  at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
  at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by normanmaurer** [comment]
@poisonriver good catch... There is really no mapping to a quic transport error here, so let me handle this a bit different. Will put up a PR shortly

**Comment by normanmaurer** [comment]
@poisonriver https://github.com/netty/netty-incubator-codec-quic/pull/736
