### ISSUE TITLE
UnsatisfiedLinkError in 0.0.69.Final 

### ISSUE THREAD

**Issue by jaymansfield** [netty/netty-incubator-codec-quic#759]
Have tried on osx-aarch_64, osx-x86_64 and windows-x86_64.

Exception in thread "main" java.lang.UnsatisfiedLinkError: 'int io.netty.incubator.codec.quic.BoringSSLNativeStaticallyReferencedJniMethods.ssl_verify_none()'
	at io.netty.incubator.codec.quic.BoringSSLNativeStaticallyReferencedJniMethods.ssl_verify_none(Native Method)
	at io.netty.incubator.codec.quic.BoringSSL.<clinit>(BoringSSL.java:28)
	at io.netty.incubator.codec.quic.QuicheQuicSslContext.<clinit>(QuicheQuicSslContext.java:83)
	at io.netty.incubator.codec.quic.QuicSslContextBuilder.keyManager(QuicSslContextBuilder.java:295)
	at io.netty.incubator.codec.quic.QuicSslContextBuilder.forServer(QuicSslContextBuilder.java:111)

Same code works in 0.0.68.Final

SelfSignedCertificate selfSignedCertificate = new SelfSignedCertificate();

            QuicSslContext context = QuicSslContextBuilder.forServer(

                            selfSignedCertificate.privateKey(), null, selfSignedCertificate.certificate())

                    .applicationProtocols("http/0.9").build();`

Dependency:

        <dependency>
            <groupId>io.netty.incubator</groupId>
            <artifactId>netty-incubator-codec-native-quic</artifactId>
            <version>0.0.69.Final</version>
            <classifier>osx-aarch_64</classifier>
        </dependency>

**Comment by normanmaurer** [comment]
hmmm that's strange. Are you sure you not have multiple versions on the class path or such ? Seems to work fine here with for example netty-incubator-codec-http3 which has it as dependency.

It successfully load the lib here:

```
20:03:04.652 [main] DEBUG io.netty.util.internal.NativeLibraryLoader -- Successfully loaded the library /var/folders/5j/vyc345kn5_s4lmv3d6zqvnpc0000gn/T/libnetty_quiche_osx_aarch_6410348663714473683264.dylib
```

**Comment by normanmaurer** [comment]
Ah I might have an idea... can you please call `Quic.ensureAvailability()` before you try to build the context ?

**Comment by jaymansfield** [comment]
> Ah I might have an idea... can you please call `Quic.ensureAvailability()` before you try to build the context ?

That seems to fix it!

**Comment by normanmaurer** [comment]
@jaymansfield thanks... in the future this should not be needed anymore after https://github.com/netty/netty-incubator-codec-quic/pull/760 is merged. Thanks for reporting
